### ISSUE TITLE
Bad configuration option: pubkeyacceptedalgorithms

### ISSUE THREAD

**Issue by HunterZeroSix** [cheretbe/packer-routeros#6]
Hello @cheretbe,  
I like your project!

I got the following error, by running a `vagrant up`:

```bash
$ vagrant init cheretbe/routeros7
...
$ vagrant up
Installing the '/home/lrettler/.vagrant.d/boxes/cheretbe-VAGRANTSLASH-routeros7/7.3.1-0/virtualbox/vagrant-routeros-0.5.0.gem' plugin. This can take a few minutes...
Installed the plugin 'vagrant-routeros (0.5.0)'!
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'cheretbe/routeros7'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'cheretbe/routeros7' version '7.3.1-0' is up to date...
==> default: Setting the name of the VM: vagrant_default_1659273910468_27105
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
==> default: Machine booted and ready!
    default: NIC MAC addresses: ["08:00:27:0C:D2:01", "08:00:27:50:15:6E"]
    default: Uploading MAC address init script as 'vagrant_provision_mac_addr.rsc'
==> default: Running provisioner: Initial provision (routeros_command)...
    default: Executing '/import vagrant_provision.rsc'
    default: command-line: line 0: Bad configuration option: pubkeyacceptedalgorithms
==> default: ROS command failed
RouterOS provisioner execution aborted
```

```
$ grep -irn 
packer-routeros/vagrantfile.template:37:  config.ssh.extra_args = ["-oPubkeyAcceptedAlgorithms=+ssh-rsa"]
```

I would like to fix the bug, but I have no experience with creating vagrant boxes or vagrant plugins.

Many thanks

**Comment by cheretbe** [comment]
Hi!

`PubkeyAcceptedAlgorithms=+ssh-rsa` option is used as a temporary fix for "sign_and_send_pubkey: no mutual signature supported" error on recent versions of ssh clients. They deprecate SHA-1 logins due to security risks, but ROS still uses it (see  https://forum.mikrotik.com/viewtopic.php?p=882513)

Looks like your ssh client doesn't support this option. Which OS are you using on your host?

Also could you please post the output of the following command?
```shell
ssh -V
```

**Comment by HunterZeroSix** [comment]
I'm currently running Ubuntu 20.04 LTS.

```
$ uname -a
Linux byllan 5.14.0-1045-oem #51-Ubuntu SMP Mon Jul 4 06:41:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```
```
$ ssh -V
OpenSSH_8.2p1 Ubuntu-4ubuntu0.5, OpenSSL 1.1.1f  31 Mar 2020
```

**Comment by cheretbe** [comment]
Yep, getting the same error on 20.04. On Ubuntu 22.04 everything is fine.
```
$ ssh -V
OpenSSH_8.9p1 Ubuntu-3, OpenSSL 3.0.2 15 Mar 2022
```
Apparently `PubkeyAcceptedAlgorithms` has been added not so long ago. I use 22.04 as my main OS and therefore need this new option. Will try to figure out how to fix this.

**Comment by cheretbe** [comment]
Added SSH client version check. This should resolve the issue.
@HunterZeroSix Please check if the fix works for you.

**Comment by HunterZeroSix** [comment]
Hi @cheretbe,  
Have you updated the plugin to Vagrant yet?  
Because I have the same error, after uninstalling and reinstalling your plugin.

```
$ vagrant plugin list
vagrant-routeros (0.5.0, global)
  - Version Constraint: 0.5.0
```

**Comment by cheretbe** [comment]
Hi there @HunterZeroSix !
No, the plugin version hasn't changed. You need to update not the plugin, but **the box file itself**.
Like this, for example
```shell
vagrant box update --box cheretbe/routeros7
```

**Comment by HunterZeroSix** [comment]
Hi @cheretbe,  
thanks for the explanation. The fix works perfectly.
